-- Innovius Capital GTM Acceleration Intelligence System
-- SQLite Memory Schema
-- Version 1.0

-- ─────────────────────────────────────────────
-- RUNS — one row per brief execution
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS runs (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  date                TEXT NOT NULL,           -- YYYY-MM-DD
  run_at              TEXT NOT NULL,           -- ISO timestamp
  hot_signals         INTEGER DEFAULT 0,
  hot_actions         INTEGER DEFAULT 0,
  sources_status      TEXT,                    -- JSON: {"slack_channels":"ok","slack_search":"ok","gmail":"ok","granola":"ok"}
  carry_over_count    INTEGER DEFAULT 0,
  companies_covered   INTEGER DEFAULT 0,       -- out of 7
  claims_kept         INTEGER DEFAULT 0,
  claims_dropped      INTEGER DEFAULT 0,
  claims_rewritten    INTEGER DEFAULT 0,
  mapping_corrections INTEGER DEFAULT 0,
  mapping_ambiguities INTEGER DEFAULT 0
);

-- ─────────────────────────────────────────────
-- EVENTS — longitudinal intelligence log
-- What happened at each company, each day
-- Accumulates over time — queryable by company + date range
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  date        TEXT NOT NULL,           -- YYYY-MM-DD
  company     TEXT NOT NULL,           -- Sewer AI | Auditoria | CloudZero | Delightree | X-Cures | ClearML | RightRev | Innovius
  event_type  TEXT NOT NULL,           -- hot_signal | hot_action | know | pattern | cross_portfolio
  content     TEXT NOT NULL,           -- the signal or action text
  source      TEXT,                    -- Slack channel, email thread, Granola meeting
  urgency     TEXT,                    -- high | medium | low
  run_id      INTEGER REFERENCES runs(id)
);

CREATE INDEX IF NOT EXISTS idx_events_company_date ON events(company, date);
CREATE INDEX IF NOT EXISTS idx_events_date ON events(date);

-- ─────────────────────────────────────────────
-- ACTIONS — checklist / carry-overs
-- Generated by each brief run as Hot Actions
-- Akash checks these off via the dashboard
-- Unchecked items carry forward to the next run
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS actions (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  date_created        TEXT NOT NULL,       -- YYYY-MM-DD
  date_completed      TEXT,                -- YYYY-MM-DD when checked off, NULL if open
  company             TEXT NOT NULL,
  content             TEXT NOT NULL,       -- the action text
  checked             INTEGER DEFAULT 0,   -- 0 = open, 1 = complete
  source_tag          TEXT,                -- "new · #channel · date" or "carry-over · date"
  run_id              INTEGER REFERENCES runs(id),
  hot_action          INTEGER DEFAULT 0,   -- 1 if unchecked AND date_created <= now-2days (time-based, updated each run)
  semantic_importance INTEGER DEFAULT 0    -- 1 if AI assessed as high urgency (set by action assessor agent)
);

CREATE INDEX IF NOT EXISTS idx_actions_checked ON actions(checked);
CREATE INDEX IF NOT EXISTS idx_actions_company ON actions(company);

-- ─────────────────────────────────────────────

-- ─────────────────────────────────────────────
-- COMPANY_STATE — last-known state per company
-- One row per company, upserted each run
-- Gives the Synthesizer a baseline before reading today's signals
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS company_state (
  company             TEXT PRIMARY KEY,
  engagement          TEXT,            -- Active | Advisory | Monitoring
  last_touch_date     TEXT,            -- YYYY-MM-DD
  last_touch_channel  TEXT,            -- #channel-name or "email" or "Granola"
  team_visibility     TEXT,            -- comma-separated Innovius team members aware
  updated_at          TEXT             -- ISO timestamp of last update
);

-- Seed company_state with all 7 portfolio companies
INSERT OR IGNORE INTO company_state (company, engagement) VALUES
  ('Sewer AI',   'Monitoring'),
  ('Auditoria',  'Monitoring'),
  ('CloudZero',  'Monitoring'),
  ('Delightree', 'Monitoring'),
  ('X-Cures',    'Monitoring'),
  ('ClearML',    'Monitoring'),
  ('RightRev',   'Monitoring');

-- ─────────────────────────────────────────────
-- RUN_QUALITY — source health and signal counts over time
-- Mirrors run-quality-log.json but queryable
-- Powers the weekly health report
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS run_quality (
  id                        INTEGER PRIMARY KEY AUTOINCREMENT,
  date                      TEXT NOT NULL,       -- YYYY-MM-DD
  day_of_week               TEXT,
  slack_channels_calls      INTEGER DEFAULT 0,
  slack_channels_signals    INTEGER DEFAULT 0,
  slack_channels_status     TEXT DEFAULT 'ok',
  slack_search_calls        INTEGER DEFAULT 0,
  slack_search_signals      INTEGER DEFAULT 0,
  slack_search_status       TEXT DEFAULT 'ok',
  gmail_calls               INTEGER DEFAULT 0,
  gmail_signals             INTEGER DEFAULT 0,
  gmail_status              TEXT DEFAULT 'ok',
  granola_calls             INTEGER DEFAULT 0,
  granola_signals           INTEGER DEFAULT 0,
  granola_status            TEXT DEFAULT 'ok',
  cloudzero_calls           INTEGER DEFAULT 0,
  cloudzero_signals         INTEGER DEFAULT 0,
  cloudzero_status          TEXT DEFAULT 'ok',
  hot_signals               INTEGER DEFAULT 0,
  hot_actions               INTEGER DEFAULT 0,
  carry_over_total          INTEGER DEFAULT 0,
  oldest_carry_over_days    INTEGER DEFAULT 0,
  channels_silent           TEXT,                -- JSON array
  sources_failed            TEXT                 -- JSON array
);

CREATE INDEX IF NOT EXISTS idx_run_quality_date ON run_quality(date);
